docker: update node.js and chrome version

diff --git a/packages/jsreport/docker/default/Dockerfile b/packages/jsreport/docker/default/Dockerfile
--- a/packages/jsreport/docker/default/Dockerfile
+++ b/packages/jsreport/docker/default/Dockerfile
@@ -1,6 +1,84 @@
-FROM jsreport/jsreport:3.11.3
+FROM node:18.16-alpine3.16
+EXPOSE 5488
+USER root
+ARG TARGETPLATFORM
 
-RUN npm install jsreport@3.12.0
+ENV GOSU_VERSION 1.12
+RUN set -eux; \
+    \
+    apk add --no-cache --virtual .gosu-deps \
+    ca-certificates \
+    dpkg \
+    gnupg \
+    ; \
+    \
+    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+    \
+    # verify the signature
+    export GNUPGHOME="$(mktemp -d)"; \
+    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+    gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+    command -v gpgconf && gpgconf --kill all || :; \
+    rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+    \
+    # clean up fetch dependencies
+    apk del --no-network .gosu-deps; \
+    \
+    chmod +x /usr/local/bin/gosu; \
+    # verify that the binary works
+    gosu --version; \
+    gosu nobody true
+
+RUN addgroup -S jsreport && adduser --shell /bin/bash -S -G jsreport jsreport
+
+# this condition is useful when the alpine registry contain different latest versions
+# per architecture, if the versions match then just use the same version number on both paths
+RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
+    export CHROMIUM_TO_INSTALL_VERSION="113.0.5672.126-r2"; \
+    elif [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
+    export CHROMIUM_TO_INSTALL_VERSION="114.0.5735.106-r0"; \
+    fi && \
+    echo "Installing Chromium $CHROMIUM_TO_INSTALL_VERSION version.." && \
+    apk update --no-cache && \
+    echo @edge http://dl-cdn.alpinelinux.org/alpine/v3.16/community >> /etc/apk/repositories && \
+    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
+    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
+    apk add --no-cache \
+    libstdc++@edge \
+    chromium@edge=$CHROMIUM_TO_INSTALL_VERSION\
+    nss \
+    freetype \
+    harfbuzz \
+    ttf-freefont@edge \
+    # just for now as we npm install from git
+    git \
+    # so user can docker exec -it test /bin/bash
+    bash
+
+RUN rm -rf /var/cache/apk/* /tmp/*
+
+RUN mkdir -p /app
+
+# we need to create the volume and give it expected owner
+# before the VOLUME step in order for the volume to be created with non-root user
+RUN mkdir /jsreport
+RUN chown jsreport:jsreport /jsreport
+RUN chmod g+s /jsreport
+
+VOLUME ["/jsreport"]
+
+ENV NPM_CONFIG_PREFIX /home/jsreport/.npm-global
+ENV PATH $PATH:/home/jsreport/.npm-global/bin
+
+WORKDIR /app
+
+ENV PUPPETEER_SKIP_DOWNLOAD true
+
+RUN npm i -g @jsreport/jsreport-cli
+RUN jsreport init
+
 RUN npm cache clean -f && rm -rf /tmp/*
 
 COPY ./packages/jsreport/docker/default/editConfig.js editConfig.js
diff --git a/packages/jsreport/docker/full/Dockerfile b/packages/jsreport/docker/full/Dockerfile
--- a/packages/jsreport/docker/full/Dockerfile
+++ b/packages/jsreport/docker/full/Dockerfile
@@ -1,8 +1,61 @@
-FROM jsreport/jsreport:3.11.3-full
+FROM ubuntu:focal
+EXPOSE 5488
+USER root
 ARG TARGETPLATFORM
 
-RUN npm install --save --save-exact jsreport@3.12.0 \
-    @jsreport/jsreport-ejs@3.0.1 \
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y gosu; \
+    rm -rf /var/lib/apt/lists/*; \
+    # verify that the binary works
+    gosu nobody true
+
+RUN adduser --disabled-password --gecos "" jsreport
+
+ENV DEBIAN_FRONTEND=noninteractive
+
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends software-properties-common wget gnupg git curl make build-essential && \
+    apt update && apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libappindicator3-1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils && \
+    # adding custom ppa repository to get access to custom version of chromium for macOS Apple Silicon hardware
+    # this ppa has builds available for architectures amd64, arm64 (which we care because we produce arm64 builds)
+    # the default puppeteer download does not work for arm, because there is no arm version for chromium
+    # https://github.com/puppeteer/puppeteer/issues/7740
+    add-apt-repository ppa:phd/chromium-browser && \
+    apt-get update && \
+    apt install -y chromium-browser=112.0.5615.49-0ubuntu0.18.04.1 chromium-codecs-ffmpeg=112.0.5615.49-0ubuntu0.18.04.1 && \
+    # fonts for chrome
+    apt install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst && \
+    # unoconv
+    apt-get -y install unoconv
+
+# cleanup
+RUN rm -rf /var/lib/apt/lists/* /var/cache/apt/* && \
+    rm -rf /src/*.deb && \
+    rm -rf /var/cache/apk/* /tmp/*
+
+RUN mkdir -p /app
+RUN mkdir -p /app/.puppeteer-cache
+
+# we need to create the volume and give it expected owner
+# before the VOLUME step in order for the volume to be created with non-root user
+RUN mkdir /jsreport
+RUN chown jsreport:jsreport /jsreport
+RUN chmod g+s /jsreport
+
+VOLUME ["/jsreport"]
+
+# node
+RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
+RUN apt-get install -y nodejs
+
+WORKDIR /app
+ENV PUPPETEER_CACHE_DIR /app/.puppeteer-cache
+
+RUN npm i -g @jsreport/jsreport-cli
+RUN jsreport init
+
+RUN npm install --save --save-exact @jsreport/jsreport-ejs@3.0.1 \
     @jsreport/jsreport-pug@4.0.0 \
     @jsreport/jsreport-aws-s3-storage@3.0.0 \
     @jsreport/jsreport-azure-storage@3.0.2 \
@@ -17,11 +70,6 @@ RUN npm install --save --save-exact jsreport@3.12.0 \
     @jsreport/jsreport-fs-store-azure-storage-persistence@3.0.0 \
     @jsreport/jsreport-unoconv@3.0.1 \
     cheerio-page-eval@1.0.0
-
-# we only add these lines because we are using FROM jsreport/jsreport:3.11.3-full
-# and we want to ensure that we don't use the deps built from the image
-RUN rm -rf /app/node_modules/oracledb
-RUN rm -rf /app/node_modules/@jsreport/jsreport-oracle-store
 
 COPY ./packages/jsreport/docker/full/install-or-build-oracledb-for-store.js install-or-build-oracledb-for-store.js
 COPY ./packages/jsreport/docker/full/build-oracledb-src.sh build-oracledb-src.sh
@@ -40,4 +88,3 @@ RUN chown -R jsreport:jsreport /app
 ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage
 
 CMD ["bash", "run.sh"]
-
